export let mealsData = [
    {
        key: 'Breakfast',
        title: 'Break Fast',
        icon: './img/icon/001-vegetable.png',
        listFood: [
            {
                key: 'pho',
                name: 'Pho (Phở)',
                urlImg: 'https://i.pinimg.com/564x/62/8d/5e/628d5e6851bbfff69727b8a825c06455.jpg',
                desc: 'Vietnamese soup consisting of broth, rice noodles, and meat, usually beef (phở bò) or chicken (phở gà). It is a popular street food in Vietnam and has gained widespread popularity internationally. The broth is typically made by simmering beef or chicken bones with various herbs and spices, such as star anise, cloves, cinnamon, and ginger.',
                price: 40000,
            },
            {
                key: 'xoi',
                name: 'Xoi (Xôi)',
                urlImg: 'https://takestwoeggs.com/wp-content/uploads/2022/02/Vietnamese-sticky-rice-with-chicken-Final-6.jpg',
                desc: 'Xôi can be enjoyed on its own or paired with different toppings, such as mung beans, coconut, sesame seeds, or meat floss, depending on the type of xôi being prepared',
                price: 15000,
            },
            {
                key: 'banhMi',
                name: 'Banh Mi (Bánh Mì)',
                urlImg: 'https://i.pinimg.com/564x/51/6b/e9/516be9340df7ef690bfe4d68ecff17eb.jpg',
                desc: 'Bánh mì sandwiches are renowned for their balance of textures and flavors, offering a delightful mix of savory, sweet, sour, and spicy elements.',
                price: 15000,
            },
            {
                key: 'banhUot',
                name: 'Banh Uot (Bánh Ướt)',
                urlImg: 'https://i.pinimg.com/564x/ce/2b/d3/ce2bd32ab494e6294db7de62eb5a9fcf.jpg',
                desc: 'roll or fold the rice noodle sheets around the fillings, creating bite-sized rolls. Each bite combines the softness of the rice noodle with the flavors of the accompanying ingredients and the zing of the dipping sauce. Bánh ướt is appreciated for its lightness and the balance of textures and flavors.',
                price: 20000,
            },
        ],
    },
    {
        key: 'RiceDish',
        title: 'Rice Dish',
        icon: './img/icon/004-fried-rice.png',
        listFood: [{
            key: 'comTam',
            name: 'Polk Rice (Cơm Tấm Sườn Nướng)',
            urlImg: 'https://i.pinimg.com/564x/52/f0/f8/52f0f84c0f51fce80c22874039095e97.jpg',
            desc: 'A popular Vietnamese dish featuring broken rice served with grilled pork.',
            price: 40000,
        },
        {
            key: 'comGa',
            name: 'Chicken Rice (Cơm Gà)',
            urlImg: 'https://i.pinimg.com/564x/b8/f4/fd/b8f4fd03bac97916d2551e9384860a00.jpg',
            desc: 'Delicious Vietnamese chicken rice made with fragrant rice and tender chicken.',
            price: 40000,
        },
        {
            key: 'comChienDuongChau',
            name: 'Cơm chiên Dương Châu',
            urlImg: 'https://i.pinimg.com/564x/45/cd/e7/45cde7f7f43c042776c001bf63beabc0.jpg',
            desc: 'A flavorful Vietnamese version of Yangzhou fried rice, a classic Chinese dish.',
            price: 40000,
        },
        {
            key: 'comKhong',
            name: 'Rice (Cơm không)',
            urlImg: 'https://i.pinimg.com/564x/a4/10/12/a410125891eb6184fecc65ec20d7f828.jpg',
            desc: 'Simple and classic plain rice, a staple in Vietnamese cuisine.',
            price: 40000,
        },],
    },
    {
        key: 'SavoryDish',
        title: 'Savory Dish',
        icon: './img/icon/005-meat.png',

        listFood: [{
            key: 'thitKhoTrung',
            name: '(Thịt Kho Trứng)',
            urlImg: 'https://i.pinimg.com/564x/b6/15/da/b615da2d704ace5b6cea148cfc888e53.jpg',
            desc: 'A traditional Vietnamese dish featuring caramelized pork and boiled eggs, often enjoyed with steamed rice.',
            price: 30000,
        },
        {
            key: 'caKhoTo',
            name: 'Braised Fish (Cá Kho Tộ)',
            urlImg: 'https://i.pinimg.com/564x/08/b5/40/08b5401552d4c714e9ddcdad5d06bb04.jpg',
            desc: 'A flavorful Vietnamese dish where fish is braised in a clay pot with a savory and slightly sweet sauce.',
            price: 30000,
        },
        {
            key: 'dauKhuonNhoiThit',
            name: 'Polk-stuffed Tofu (Đậu Khuôn Nhồi Thịt)',
            urlImg: 'https://i.pinimg.com/564x/bc/27/47/bc2747225ad25c32fdff52867d0bac77.jpg',
            desc: 'Tofu pockets stuffed with seasoned ground meat, a delicious and satisfying Vietnamese dish.',
            price: 30000,
        },
        {
            key: 'boXaoBongThienLy',
            name: '(Bò xào Bông Thiên Lý)',
            urlImg: 'https://i.pinimg.com/564x/23/82/09/2382093c402c3367eaf7ecda5411e8f0.jpg',
            desc: 'Beef stir-fried with Chinese chives, creating a tasty and aromatic Vietnamese dish.',
            price: 30000,
        },],
    },
    {
        key: 'Soup',
        title: 'Soup',
        icon: './img/icon/002-hot-soup.png',

        listFood: [{
            key: 'canhBiDo',
            name: 'Red Pumpkin Soup (Canh Bí Đỏ)',
            urlImg: 'https://images.squarespace-cdn.com/content/v1/52d3fafee4b03c7eaedee15f/44c0cbc4-fd45-4856-bdef-a5f0b74cccb6/2022_12_06EOS+M505096.jpg?format=2500w',
            desc: 'Vietnamese dish known for its comforting and nutritious qualities. It typically features red pumpkin (bí đỏ) as the main ingredient, along with various herbs and sometimes meat or seafood',
            price: 15000,
        },
        {
            key: 'canhKhoQua',
            name: 'Bitter Melon Soup (Canh Khổ Qua)',
            urlImg: 'https://i.pinimg.com/736x/ca/ab/91/caab9126b51662b8266e365850205345.jpg',
            desc: 'Vietnamese soup made with bitter melon (khổ qua), a unique and bitter-tasting vegetable. The soup is often prepared with a variety of ingredients such as pork, shrimp, or fish, along with herbs and spices. ',
            price: 15000,
        },
        {
            key: 'canhChuaCaLoc',
            name: 'Snakehead Fish Soup (Canh Chua Cá Lóc)',
            urlImg: 'https://i.pinimg.com/564x/d7/fd/a2/d7fda2ec14e1d667aa29c87c471d57b9.jpg',
            desc: 'Vietnamese dish that features the freshwater snakehead fish (cá lóc) in a sour tamarind-based broth. The soup is known for its delightful combination of sour, sweet, and savory flavors. Besides the fish, it typically includes various vegetables such as tomatoes, pineapples, and okra, as well as herbs like Vietnamese coriander. Canh Chua is a popular and refreshing soup in Vietnamese cuisine, offering a balance of tangy and savory tastes.',
            price: 15000,
        },
        {
            key: 'canhRauNgot',
            name: 'Water Spinach Soup (Canh Rau Ngót)',
            urlImg: 'https://i.pinimg.com/564x/32/c5/88/32c58851d93d59cd8ccac2d3c072c1f3.jpg',
            desc: 'Vietnamese soup that highlights water spinach (rau ngót) as the main ingredient. Water spinach, also known as morning glory, is a leafy green vegetable with hollow stems. The soup is often made with a simple and clear broth, featuring water spinach along with other complementary vegetables and sometimes protein sources like shrimp or pork. It is a light and nutritious dish commonly enjoyed in Vietnamese households, appreciated for its fresh and vibrant flavors.',
            price: 15000,
        },],
    },
    {
        key: 'Snack',
        title: 'Snack',
        icon: './img/icon/006-nachos.png',

        listFood: [{
            key: 'banhTrangTron',
            name: 'Mixed Rice Paper Salad (Bánh Tráng Trộn)',
            urlImg: 'https://i.pinimg.com/564x/62/b0/58/62b05832fae87fdabf74517176f30c1f.jpg',
            desc: 'Bánh Tráng Trộn is a popular street food snack in Vietnam. It involves shredded rice paper mixed with a variety of ingredients such as green mango, herbs, peanuts, quail eggs, dried shrimp, and a flavorful dressing typically made with soy sauce, chili, and other seasonings. The dish is known for its unique textures and combination of sweet, salty, spicy, and sour flavors. It is a popular and refreshing snack enjoyed for its bold taste and crunchy texture.',
            price: 20000,
        },
        {
            key: 'xoaiLac',
            name: 'Mango Shake (Xoài Lắc)',
            urlImg: 'https://i.pinimg.com/564x/df/b4/eb/dfb4ebe313a169dc207db790b4048206.jpg',
            desc: 'It is made of ripe mangoes cut into thin slices and mixed with salt, chili powder, and shrimp paste. It has a sweet, sour, spicy, and savory taste that is very addictive. You can find it in many street vendors or make it at home with simple ingredients1',
            price: 20000,
        },
        {
            key: 'cheTroiNuoc',
            name: 'Glutinous Rice Balls (Chè trôi nước)',
            urlImg: 'https://i.pinimg.com/564x/99/bc/0a/99bc0a849def7f58e9585353c3b3841c.jpg',
            desc: 'Chè Trôi Nước is a traditional Vietnamese dessert. The dish consists of small, round glutinous rice dumplings filled with mung bean paste, often served in a warm and sweet ginger-infused syrup. The dumplings are translucent and "float" in the soup, giving the dessert its distinctive name. Chè Trôi Nước is appreciated for its comforting sweetness and the combination of textures between the chewy dumplings and the fragrant ginger syrup. It is commonly enjoyed as a warm treat, especially during festive occasions.',
            price: 20000,
        },
        {
            key: 'comChayChaBong',
            name: 'Rice Crackers with Pork Floss. (Cơm Cháy Chà Bông)',
            urlImg: 'https://i.pinimg.com/564x/66/28/19/662819b2431e7e22f240cd8b7154bb48.jpg',
            desc: 'Cơm Cháy refers to crispy rice crackers, and Chà Bông is shredded or flossy pork. In this Vietnamese dish, crispy rice crackers are typically served with a topping of savory and slightly sweet pork floss. The pork floss is often seasoned and dried to achieve a fluffy, fibrous texture. The combination of the crunchy rice crackers and the flavorful pork floss creates a delightful contrast in both texture and taste. It is a popular snack or side dish enjoyed for its savory and satisfying qualities.',
            price: 20000,
        },],
    },
];
